### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by huo852yan** [yael-vinker/SceneSketch#2]
Can you offer an installation way via pip?
Thank you!

**Comment by huuquan1994** [comment]
@huo852yan 
I can't use docker so this is what I did to install (Assuming you're using `conda` with an environment `clipascene` with python >= 3.7)

## 1. Install the required packages
```
conda activate clipascene

git clone https://github.com/yael-vinker/SceneSketch
cd SceneSketch/

pip install -r requirements.txt
```
## 2. Install [pydiffvg](https://github.com/BachiLi/diffvg/tree/master/pydiffvg) and [OpenAI CLIP](https://github.com/openai/CLIP) packages
### pydiffvg
```
git clone https://github.com/BachiLi/diffvg
cd diffvg/

git submodule update --init --recursive
conda install -y numpy
conda install -y scikit-image
conda install -y -c anaconda cmake
conda install -y -c conda-forge ffmpeg
pip install svgwrite
pip install svgpathtools
pip install cssutils
pip install numba
pip install torch-tools
pip install visdom

DIFFVG_CUDA=1 python setup.py install # need to use DIFFVG_CUDA=1 to run with NVIDIA GPU
```

### OpenAI CLIP
```
pip install ftfy regex tqdm

cd CLIP_/
python setup.py install
```

If you have a warning related to `protobuf`, run `pip install --upgrade "protobuf<=3.20.1"`

From now, I think you're good to go.

**Comment by yael-vinker** [comment]
Thanks @huuquan1994 for your help!
@huo852yan , sorry for missing your question, and thanks for your interest in our work! If you need any additional assistance with installation please let me know
